### PR TITLE
Update to Java Mongo Driver 3.2.2

### PR DESCRIPTION
**Pull request by arnzel**

### CODE REVIEW

**Comment by ctrimble** [comment]
@arnzel Thanks for the PR.  This seems to break compatibility with the 2.X driver and is causing the integration tests to fail.  Let me see what needs to be done to get those issues resolved.

**Comment by arnzel** [comment]
Oh, i did not See any Tests running in the travis build.

**Comment by ctrimble** [comment]
They are not running on Travis yet.  Instructions are at the bottom of the README.

The example needs a dependency update to work.  I have opened an issue to see if I can get more frequent releases.  If not, I will remove the library from this project and get things moving again.

**Comment by ctrimble** [comment]
Release request with Jongo: https://github.com/bguerout/jongo/issues/285

**Comment by ctrimble** [comment]
I have opened #10 to address this issue.  Sorry for opening a PR and not getting you into the history.  I didn't want to drop the error handling around the client creation code.

**Comment by ctrimble** [comment]
I am going to close this PR, since it is addressed by #10.

**Pull request closed without merging**
